# -*- coding: utf-8 -*-
# City names per language; anything absent falls back to the English spelling.
CITY = {
"de_DE":{"Rome":"Rom","Thermaic Gulf":"Thermaischer Golf","Constantinople":"Konstantinopel","Carthage":"Karthago","Nineveh":"Ninive","Axum":"Aksum","Madrid":"Madrid","Bucharest":"Bukarest","Syracuse":"Syrakus","Florence":"Florenz","Veliko Tarnovo":"Weliko Tarnowo","Baghdad":"Bagdad","Reykjavik":"Reykjavík","Algiers":"Algier","Lisbon":"Lissabon","Athens":"Athen","Tbilisi":"Tiflis","Warsaw":"Warschau","Moscow":"Moskau","Tehran":"Teheran","Seville":"Sevilla","Vienna":"Wien","Naples":"Neapel","Gondar":"Gonder","Kyiv":"Kyjiw","Fez":"Fès","Krakow":"Krakau","Copenhagen":"Kopenhagen","Marrakesh":"Marrakesch","Sarai on the lower Volga":"Sarai an der unteren Wolga"},
"es_ES":{"Memphis":"Menfis","Rome":"Roma","Thermaic Gulf":"golfo Termaico","Constantinople":"Constantinopla","Carthage":"Cartago","Nineveh":"Nínive","Axum":"Aksum","London":"Londres","Dublin":"Dublín","Paris":"París","Berlin":"Berlín","Bucharest":"Bucarest","Syracuse":"Siracusa","Florence":"Florencia","Baghdad":"Bagdad","Reykjavik":"Reikiavik","Algiers":"Argel","Lisbon":"Lisboa","Athens":"Atenas","Alexandria":"Alejandría","Tbilisi":"Tiflis","Warsaw":"Varsovia","Moscow":"Moscú","Tehran":"Teherán","Seville":"Sevilla","Uppsala":"Upsala","Vienna":"Viena","Naples":"Nápoles","Kyiv":"Kiev","Krakow":"Cracovia","Copenhagen":"Copenhague","Marrakesh":"Marrakech","Sarai on the lower Volga":"Sarai, en el bajo Volga"},
"fr_FR":{"Thermaic Gulf":"golfe Thermaïque","Nineveh":"Ninive","Susa":"Suse","Axum":"Aksoum","London":"Londres","Bucharest":"Bucarest","Veliko Tarnovo":"Veliko Tarnovo","Baghdad":"Bagdad","Algiers":"Alger","Lisbon":"Lisbonne","Athens":"Athènes","Alexandria":"Alexandrie","Tbilisi":"Tbilissi","Warsaw":"Varsovie","Moscow":"Moscou","Tehran":"Téhéran","Seville":"Séville","Vienna":"Vienne","Naples":"Naples","Fez":"Fès","Krakow":"Cracovie","Copenhagen":"Copenhague","Marrakesh":"Marrakech","Sarai on the lower Volga":"Saraï, sur la basse Volga"},
"it_IT":{"Memphis":"Menfi","Tehran":"Teheran","Rome":"Roma","Thermaic Gulf":"Golfo Termaico","Constantinople":"Costantinopoli","Carthage":"Cartagine","Nineveh":"Ninive","Axum":"Axum","London":"Londra","Dublin":"Dublino","Paris":"Parigi","Berlin":"Berlino","Bucharest":"Bucarest","Syracuse":"Siracusa","Florence":"Firenze","Baghdad":"Baghdad","Algiers":"Algeri","Lisbon":"Lisbona","Athens":"Atene","Alexandria":"Alessandria","Warsaw":"Varsavia","Moscow":"Mosca","Seville":"Siviglia","Naples":"Napoli","Kyiv":"Kiev","Krakow":"Cracovia","Copenhagen":"Copenaghen","Sarai on the lower Volga":"Sarai sul basso Volga"},
"pl_PL":{"Axum":"Aksum","Tehran":"Teheran","Rome":"Rzym","Thermaic Gulf":"Zatoka Termajska","Constantinople":"Konstantynopol","Carthage":"Kartagina","Memphis":"Memfis","Nineveh":"Niniwa","Susa":"Suza","London":"Londyn","Madrid":"Madryt","Paris":"Paryż","Bucharest":"Bukareszt","Syracuse":"Syrakuzy","Florence":"Florencja","Veliko Tarnovo":"Wielkie Tyrnowo","Baghdad":"Bagdad","Algiers":"Algier","Lisbon":"Lizbona","Athens":"Ateny","Alexandria":"Aleksandria","Warsaw":"Warszawa","Moscow":"Moskwa","Seville":"Sewilla","Vienna":"Wiedeń","Naples":"Neapol","Gondar":"Gonder","Kyiv":"Kijów","Krakow":"Kraków","Copenhagen":"Kopenhaga","Marrakesh":"Marrakesz","Sarai on the lower Volga":"Saraj nad dolną Wołgą"},
"pt_BR":{"Memphis":"Mênfis","Rome":"Roma","Thermaic Gulf":"golfo Termaico","Constantinople":"Constantinopla","Carthage":"Cartago","Nineveh":"Nínive","Axum":"Axum","London":"Londres","Madrid":"Madri","Berlin":"Berlim","Bucharest":"Bucareste","Syracuse":"Siracusa","Florence":"Florença","Baghdad":"Bagdá","Reykjavik":"Reiquiavique","Algiers":"Argel","Lisbon":"Lisboa","Athens":"Atenas","Alexandria":"Alexandria","Warsaw":"Varsóvia","Moscow":"Moscou","Tehran":"Teerã","Seville":"Sevilha","Uppsala":"Upsala","Vienna":"Viena","Naples":"Nápoles","Kyiv":"Kiev","Krakow":"Cracóvia","Copenhagen":"Copenhague","Marrakesh":"Marraquexe","Sarai on the lower Volga":"Sarai, no baixo Volga"},
"uk_UA":{"Rome":"Рим","Populonia":"Популонія","Thermaic Gulf":"Термайська затока","Constantinople":"Константинополь","Carthage":"Карфаген","Memphis":"Мемфіс","Nineveh":"Ніневія","Susa":"Сузи","Axum":"Аксум","London":"Лондон","Dublin":"Дублін","Madrid":"Мадрид","Paris":"Париж","Berlin":"Берлін","Bucharest":"Бухарест","Ankara":"Анкара","Syracuse":"Сиракузи","Florence":"Флоренція","Veliko Tarnovo":"Велико-Тирново","Rouen":"Руан","Baghdad":"Багдад","Reykjavik":"Рейк'явік","Gao":"Гао","Algiers":"Алжир","Lisbon":"Лісабон","Athens":"Афіни","Alexandria":"Александрія","Tbilisi":"Тбілісі","Warsaw":"Варшава","Moscow":"Москва","Tehran":"Тегеран","Seville":"Севілья","Uppsala":"Уппсала","Vienna":"Відень","Naples":"Неаполь","Budapest":"Будапешт","Gondar":"Гондер","Kyiv":"Київ","Fez":"Фес","Krakow":"Краків","Trondheim":"Тронгейм","Copenhagen":"Копенгаген","Marrakesh":"Марракеш","Sarai on the lower Volga":"Сарай на нижній Волзі"},
"ja_JP":{"Rome":"ローマ","Populonia":"ポプロニア","Thermaic Gulf":"テルマイコス湾","Constantinople":"コンスタンティノープル","Carthage":"カルタゴ","Memphis":"メンフィス","Nineveh":"ニネヴェ","Susa":"スーサ","Axum":"アクスム","London":"ロンドン","Dublin":"ダブリン","Madrid":"マドリード","Paris":"パリ","Berlin":"ベルリン","Bucharest":"ブカレスト","Ankara":"アンカラ","Syracuse":"シラクサ","Florence":"フィレンツェ","Veliko Tarnovo":"ヴェリコ・タルノヴォ","Rouen":"ルーアン","Baghdad":"バグダード","Reykjavik":"レイキャヴィク","Gao":"ガオ","Algiers":"アルジェ","Lisbon":"リスボン","Athens":"アテネ","Alexandria":"アレクサンドリア","Tbilisi":"トビリシ","Warsaw":"ワルシャワ","Moscow":"モスクワ","Tehran":"テヘラン","Seville":"セビリア","Uppsala":"ウプサラ","Vienna":"ウィーン","Naples":"ナポリ","Budapest":"ブダペスト","Gondar":"ゴンダール","Kyiv":"キーウ","Fez":"フェズ","Krakow":"クラクフ","Trondheim":"トロンハイム","Copenhagen":"コペンハーゲン","Marrakesh":"マラケシュ","Sarai on the lower Volga":"ヴォルガ川下流のサライ"},
"ko_KR":{"Rome":"로마","Populonia":"포풀로니아","Thermaic Gulf":"테르마이코스만","Constantinople":"콘스탄티노플","Carthage":"카르타고","Memphis":"멤피스","Nineveh":"니네베","Susa":"수사","Axum":"악숨","London":"런던","Dublin":"더블린","Madrid":"마드리드","Paris":"파리","Berlin":"베를린","Bucharest":"부쿠레슈티","Ankara":"앙카라","Syracuse":"시라쿠사","Florence":"피렌체","Veliko Tarnovo":"벨리코터르노보","Rouen":"루앙","Baghdad":"바그다드","Reykjavik":"레이캬비크","Gao":"가오","Algiers":"알제","Lisbon":"리스본","Athens":"아테네","Alexandria":"알렉산드리아","Tbilisi":"트빌리시","Warsaw":"바르샤바","Moscow":"모스크바","Tehran":"테헤란","Seville":"세비야","Uppsala":"웁살라","Vienna":"빈","Naples":"나폴리","Budapest":"부다페스트","Gondar":"곤다르","Kyiv":"키이우","Fez":"페스","Krakow":"크라쿠프","Trondheim":"트론헤임","Copenhagen":"코펜하겐","Marrakesh":"마라케시","Sarai on the lower Volga":"볼가강 하류의 사라이"},
"zh_Hans_CN":{"Rome":"罗马","Populonia":"波普洛尼亚","Thermaic Gulf":"塞尔迈湾","Constantinople":"君士坦丁堡","Carthage":"迦太基","Memphis":"孟菲斯","Nineveh":"尼尼微","Susa":"苏萨","Axum":"阿克苏姆","London":"伦敦","Dublin":"都柏林","Madrid":"马德里","Paris":"巴黎","Berlin":"柏林","Bucharest":"布加勒斯特","Ankara":"安卡拉","Syracuse":"锡拉库萨","Florence":"佛罗伦萨","Veliko Tarnovo":"大特尔诺沃","Rouen":"鲁昂","Baghdad":"巴格达","Reykjavik":"雷克雅未克","Gao":"加奥","Algiers":"阿尔及尔","Lisbon":"里斯本","Athens":"雅典","Alexandria":"亚历山大","Tbilisi":"第比利斯","Warsaw":"华沙","Moscow":"莫斯科","Tehran":"德黑兰","Seville":"塞维利亚","Uppsala":"乌普萨拉","Vienna":"维也纳","Naples":"那不勒斯","Budapest":"布达佩斯","Gondar":"贡德尔","Kyiv":"基辅","Fez":"非斯","Krakow":"克拉科夫","Trondheim":"特隆赫姆","Copenhagen":"哥本哈根","Marrakesh":"马拉喀什","Sarai on the lower Volga":"伏尔加河下游的萨莱"},
"zh_Hant_HK":{"Rome":"羅馬","Populonia":"波普洛尼亞","Thermaic Gulf":"塞爾邁灣","Constantinople":"君士坦丁堡","Carthage":"迦太基","Memphis":"孟菲斯","Nineveh":"尼尼微","Susa":"蘇薩","Axum":"阿克蘇姆","London":"倫敦","Dublin":"都柏林","Madrid":"馬德里","Paris":"巴黎","Berlin":"柏林","Bucharest":"布加勒斯特","Ankara":"安卡拉","Syracuse":"錫拉庫薩","Florence":"佛羅倫斯","Veliko Tarnovo":"大特爾諾沃","Rouen":"魯昂","Baghdad":"巴格達","Reykjavik":"雷克雅未克","Gao":"加奧","Algiers":"阿爾及爾","Lisbon":"里斯本","Athens":"雅典","Alexandria":"亞歷山大","Tbilisi":"第比利斯","Warsaw":"華沙","Moscow":"莫斯科","Tehran":"德黑蘭","Seville":"塞維利亞","Uppsala":"烏普薩拉","Vienna":"維也納","Naples":"拿坡里","Budapest":"布達佩斯","Gondar":"貢德爾","Kyiv":"基輔","Fez":"非斯","Krakow":"克拉科夫","Trondheim":"特隆赫姆","Copenhagen":"哥本哈根","Marrakesh":"馬拉喀什","Sarai on the lower Volga":"伏爾加河下游的薩萊"},
}
# Civilizations the game does not ship (this repo's own), and all of Ukrainian.
MOD_CIVS = {
"de_DE":{"ETRUSCANS":"Etrusker","TUSCANY":"Toskana","BYZANTIUM":"Byzanz"},
"es_ES":{"ETRUSCANS":"etruscos","TUSCANY":"Toscana","BYZANTIUM":"Bizancio"},
"fr_FR":{"ETRUSCANS":"Étrusques","TUSCANY":"Toscane","BYZANTIUM":"Byzance"},
"it_IT":{"ETRUSCANS":"Etruschi","TUSCANY":"Toscana","BYZANTIUM":"Bisanzio"},
"pl_PL":{"ETRUSCANS":"Etruskowie","TUSCANY":"Toskania","BYZANTIUM":"Bizancjum"},
"pt_BR":{"ETRUSCANS":"etruscos","TUSCANY":"Toscana","BYZANTIUM":"Bizâncio"},
"ja_JP":{"ETRUSCANS":"エトルリア","TUSCANY":"トスカーナ","BYZANTIUM":"ビザンティウム"},
"ko_KR":{"ETRUSCANS":"에트루리아","TUSCANY":"토스카나","BYZANTIUM":"비잔티움"},
"zh_Hans_CN":{"ETRUSCANS":"伊特鲁里亚","TUSCANY":"托斯卡纳","BYZANTIUM":"拜占庭"},
"zh_Hant_HK":{"ETRUSCANS":"伊特魯里亞","TUSCANY":"托斯卡納","BYZANTIUM":"拜占庭"},
"uk_UA":{"ROME":"Рим","ETRUSCANS":"Етруски","GREECE":"Греція","BYZANTIUM":"Візантія","CARTHAGE":"Карфаген","EGYPT":"Єгипет","ASSYRIA":"Ассирія","PERSIA":"Персія","AKSUM":"Аксум","MISSISSIPPIAN":"Міссісіпська культура","HEIAN":"Японія Хейан","MAURYA":"Маур'ї","HAN":"Хань","MAYA":"Мая","KHMER":"Кхмери","SILLA":"Сілла","TONGA":"Тонга","TUSCANY":"Тоскана","BULGARIA":"Болгарія","SPAIN":"Іспанія","NORMAN":"Нормани","ABBASID":"Аббасиди","ICELAND":"Ісландія","MONGOLIA":"Монголія","SONGHAI":"Сонгаї","PIRATE_REPUBLIC":"Піратська республіка","SENGOKU":"Японія Сенгоку","MAJAPAHIT":"Маджапагіт","CHOLA":"Чола","GORYEO":"Корьо","DAI_VIET":"Дайв'єт","INCA":"Інки","HAWAII":"Гаваї","SHAWNEE":"Шоні","MING":"Мін","GREAT_BRITAIN":"Велика Британія","AMERICA":"Америка","FRENCH_EMPIRE":"Французька імперія","PRUSSIA":"Пруссія","RUSSIA":"Росія","OTTOMANS":"Османи","QAJAR":"Каджари","MEXICO":"Мексика","JOSEON":"Чосон","MEIJI":"Японія Мейдзі","QING":"Цін","SIAM":"Сіам","MUGHAL":"Моголи","NEPAL":"Непал","BUGANDA":"Буганда"},
}
